_wandb:
    value:
        cli_version: 0.18.6
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 13
                - 16
                - 23
                - 35
                - 55
            "4": 3.8.20
            "5": 0.18.6
            "8":
                - 5
            "12": 0.18.6
            "13": linux-x86_64
algorithm:
    value:
        clip_param: 0.2
        desired_kl: 0.01
        entropy_coef: 0.01
        gamma: 0.99
        lam: 0.95
        learning_rate: 6e-05
        max_grad_norm: 1
        num_learning_epochs: 5
        num_mini_batches: 4
        schedule: adaptive
        use_clipped_value_loss: true
        value_loss_coef: 1
asset:
    value:
        angular_damping: 0
        armature: 0.001
        collapse_fixed_joints: true
        data_path: '{LEGGED_GYM_ROOT_DIR}/resources/data/motion_data1.npy'
        default_dof_drive_mode: 3
        density: 0.001
        disable_gravity: false
        file: '{LEGGED_GYM_ROOT_DIR}/resources/robots/h1_2/h1_2_12dof.urdf'
        fix_base_link: false
        flip_visual_attachments: false
        foot_name: ankle_roll
        knee_name: knee
        linear_damping: 0
        max_angular_velocity: 1000
        max_linear_velocity: 1000
        name: h1_2
        penalize_contacts_on:
            - hip
            - knee
        replace_cylinder_with_capsule: true
        self_collisions: 0
        terminate_after_contacts_on:
            - pelvis
        thickness: 0.01
commands:
    value:
        curriculum: false
        heading_command: true
        max_curriculum: 1
        num_commands: 4
        ranges:
            ang_vel_yaw:
                - -1
                - 1
            heading:
                - -3.14
                - 3.14
            lin_vel_x:
                - 2
                - 6
            lin_vel_y:
                - -1
                - 1
        resampling_time: 10
control:
    value:
        action_scale: 0.25
        control_type: P
        damping:
            ankle_pitch_joint: 2
            ankle_roll_joint: 2
            hip_pitch_joint: 2.5
            hip_roll_joint: 2.5
            hip_yaw_joint: 2.5
            knee_joint: 4
        decimation: 8
        stiffness:
            ankle_pitch_joint: 40
            ankle_roll_joint: 40
            hip_pitch_joint: 200
            hip_roll_joint: 200
            hip_yaw_joint: 200
            knee_joint: 300
domain_rand:
    value:
        added_mass_range:
            - -1
            - 3
        friction_range:
            - 0.1
            - 1.25
        max_push_vel_xy: 1.5
        push_interval: 251
        push_interval_s: 5
        push_robots: true
        randomize_base_mass: true
        randomize_friction: true
env:
    value:
        env_spacing: 3
        episode_length_s: 20
        frame_stack: 15
        num_actions: 12
        num_envs: 4096
        num_height_points: 187
        num_observations: 47
        num_privileged_obs: 237
        num_rma_obs: 237
        send_timeouts: true
        test: false
init_state:
    value:
        ang_vel:
            - 0
            - 0
            - 0
        default_joint_angles:
            left_ankle_pitch_joint: -0.2
            left_ankle_roll_joint: 0
            left_elbow_pitch_joint: 0.3
            left_hip_pitch_joint: -0.16
            left_hip_roll_joint: 0
            left_hip_yaw_joint: 0
            left_knee_joint: 0.36
            left_shoulder_pitch_joint: 0.4
            left_shoulder_roll_joint: 0
            left_shoulder_yaw_joint: 0
            right_ankle_pitch_joint: -0.2
            right_ankle_roll_joint: 0
            right_elbow_pitch_joint: 0.3
            right_hip_pitch_joint: -0.16
            right_hip_roll_joint: 0
            right_hip_yaw_joint: 0
            right_knee_joint: 0.36
            right_shoulder_pitch_joint: 0.4
            right_shoulder_roll_joint: 0
            right_shoulder_yaw_joint: 0
            torso_joint: 0
        lin_vel:
            - 0
            - 0
            - 0
        pos:
            - 0
            - 0
            - 1.05
        rot:
            - 0
            - 0
            - 0
            - 1
noise:
    value:
        add_noise: true
        noise_level: 1
        noise_scales:
            ang_vel: 0.2
            dof_pos: 0.01
            dof_vel: 1.5
            gravity: 0.05
            height_measurements: 0.1
            lin_vel: 0.1
normalization:
    value:
        clip_actions: 100
        clip_observations: 100
        obs_scales:
            ang_vel: 0.25
            dof_pos: 1
            dof_vel: 0.05
            height_measurements: 5
            lin_vel: 2
policy:
    value:
        activation: elu
        actor_hidden_dims:
            - 128
            - 32
        critic_hidden_dims:
            - 128
            - 32
        init_noise_std: 0.8
        rnn_hidden_size: 256
        rnn_num_layers: 1
        rnn_type: lstm
rewards:
    value:
        base_height_target: 1
        cycle_time: 0.6
        feet_high_control_lim: 0.2
        feet_high_frame_num: 50
        max_contact_force: 100
        max_dist: 0.26
        min_dist: 0.19
        only_positive_rewards: true
        scales:
            action_rate: -0.01
            alive: 40
            ang_vel_xy: -0.05
            base_height: -30
            collision: 0
            contact_no_vel: -0.2
            dof_acc: -2.5e-07
            dof_pos_limits: -5
            dof_vel: -0.001
            feet_air_time: 1
            feet_high_control: 0
            feet_stumble: -0
            hip_pos: -1
            knee_distance: 0
            lin_vel_z: -2
            orientation: -1
            stand_still: -0
            termination: -0
            torques: -1e-05
            tracking_ang_vel: 16
            tracking_lin_vel: 32
        soft_dof_pos_limit: 0.9
        soft_dof_vel_limit: 1
        soft_torque_limit: 1
        tracking_sigma: 0.2
rma:
    value:
        num_latents: 128
runner:
    value:
        algorithm_class_name: RMA
        checkpoint: -1
        experiment_name: H12_rma
        load_run: 2024-12-26_17-16-14_wyy-rma-teacher
        max_iterations: 1000
        num_steps_per_env: 24
        policy_class_name: ActorCriticRecurrentRMA
        resume: true
        resume_path: null
        run_name: wyy-rma-teacher
        save_interval: 200
runner_class_name:
    value: RMARunner
seed:
    value: 1
sim:
    value:
        dt: 0.0025
        gravity:
            - 0
            - 0
            - -9.81
        physx:
            bounce_threshold_velocity: 0.5
            contact_collection: 2
            contact_offset: 0.01
            default_buffer_size_multiplier: 5
            max_depenetration_velocity: 1
            max_gpu_contact_pairs: 8388608
            num_position_iterations: 4
            num_threads: 10
            num_velocity_iterations: 0
            rest_offset: 0
            solver_type: 1
        substeps: 1
        up_axis: 1
terrain:
    value:
        border_size: 20
        curriculum: true
        dynamic_friction: 1
        fix_level: 0
        horizontal_scale: 0.1
        max_init_terrain_level: 5
        measure_heights: true
        measured_points_x:
            - -0.8
            - -0.7
            - -0.6
            - -0.5
            - -0.4
            - -0.3
            - -0.2
            - -0.1
            - 0
            - 0.1
            - 0.2
            - 0.3
            - 0.4
            - 0.5
            - 0.6
            - 0.7
            - 0.8
        measured_points_y:
            - -0.5
            - -0.4
            - -0.3
            - -0.2
            - -0.1
            - 0
            - 0.1
            - 0.2
            - 0.3
            - 0.4
            - 0.5
        mesh_type: trimesh
        num_cols: 20
        num_rows: 10
        num_sub_terrains: 200
        restitution: 0
        selected: false
        slope_treshold: 0.75
        static_friction: 1
        terrain_kwargs: null
        terrain_length: 8
        terrain_proportions:
            - 0
            - 1
        terrain_width: 8
        vertical_scale: 0.005
viewer:
    value:
        lookat:
            - 11
            - 5
            - 3
        pos:
            - 10
            - 0
            - 6
        ref_env: 0
